# Generated by Django 3.2 on 2021-05-05 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('logo', models.ImageField(blank=True, default='company_images/default.gif', upload_to='company_images', verbose_name='Логотип')),
                ('employee_count', models.IntegerField(verbose_name='Количество сотрудников')),
                ('location', models.CharField(max_length=100, verbose_name='Город')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='owner_of_company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'компания',
                'verbose_name_plural': 'компании',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('code', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='speciality_images')),
            ],
            options={
                'verbose_name': 'специализация',
                'verbose_name_plural': 'специализации',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Название вакансии')),
                ('salary_from', models.IntegerField(blank=True, null=True, verbose_name='Зарплата от')),
                ('salary_to', models.IntegerField(blank=True, null=True, verbose_name='Зарплата до')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('skills', models.TextField(blank=True, null=True, verbose_name='Навыки')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание вакансии')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='vacancies.company')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='vacancies.specialty', verbose_name='Специализация')),
            ],
            options={
                'verbose_name': 'вакансия',
                'verbose_name_plural': 'вакансии',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('surname', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('status', models.CharField(choices=[('Не ищу работу', 'Не ищу работу'), ('Рассматриваю предложения', 'Рассматриваю предложения'), ('Ищу работу', 'Ищу работу')], max_length=200, null=True, verbose_name='Статус')),
                ('salary', models.IntegerField(blank=True, null=True, verbose_name='Ожидаемая зарплата')),
                ('education', models.TextField(blank=True, verbose_name='Образование')),
                ('grade', models.CharField(choices=[('Стажер', 'Стажер'), ('Джуниор', 'Джуниор'), ('Мидл', 'Мидл'), ('Синьор', 'Синьор'), ('Лид', 'Лид')], max_length=200, null=True, verbose_name='Квалификация')),
                ('experience', models.TextField(blank=True, verbose_name='Опыт работы')),
                ('portfolio', models.URLField(blank=True, verbose_name='Портфолио')),
                ('specialty', models.ForeignKey(default='backend', on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='vacancies.specialty', verbose_name='Специализация')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'резюме',
                'verbose_name_plural': 'резюме',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('written_username', models.CharField(max_length=200, verbose_name='Имя')),
                ('written_phone', models.CharField(max_length=200, verbose_name='Телефон')),
                ('written_cover_letter', models.TextField(blank=True, null=True, verbose_name='Сопроводительное письмо')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='vacancies.vacancy')),
            ],
            options={
                'verbose_name': 'отклик',
                'verbose_name_plural': 'отклики',
            },
        ),
    ]
